version: "3.9"

services:
  app:
    build: .
    container_name: bookstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: bookstore-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    ports:
      - "3307:3306"   # Host port 3307 → Container port 3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
